apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: wireviz
  name: wireviz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireviz
  template:
    metadata:
      labels:
        app: wireviz
    spec:
      containers:
      - image: yuzutech/kroki-wireviz
        name: wireviz
        ports:
        - containerPort: 8006
      restartPolicy: Always
