name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '*'

jobs:
  test-containers:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Upgrade buildah
      run: ./upgrade-buildah.sh
    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: docker.io/yuzutech/kroki
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./server/ops/docker/jdk11-jammy/Dockerfile
        context: server
        extra-args: |
          --ulimit="nofile=65535:65535"
          --runtime runc
          --build-context nomnoml="./nomnoml"
          --build-context vega="./vega"
          --build-context dbml="./dbml"
          --build-context wavedrom="./wavedrom"
          --build-context bytefield="./bytefield"
          --build-context kroki-src="."
    - name: 'Setup Node.js 16'
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install Node dependencies
      run: npm install

    - name: Run smoke tests
      run: make smokeTests

    # This ugly bit is necessary if you don't want your cache to grow forever until it hits GitHub's limit of 5GB.
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
